### ISSUE TITLE
Estrutura da aplicação front-end - React

### ISSUE THREAD

**Issue by silvablack** [softwaredobem/boraajudar-client#2]
Saudações.

Gostaria de discutir sobre a estrutura do front-end.
Um modelo menos complexo para pequenos projetos:
Ex: (Estrutura básica criada pelo comando **_create-react-app_**)
my-app/
  README.md
  node_modules/
  package.json
  .gitignore
  public/
    favicon.ico
    index.html
  src/
    App.css
    App.js
    App.test.js
    index.css
    index.js
    logo.svg

Ou um modelo mais escalável com módulos compartilhados:
Ex:
app
├── config
│   └── routes.js
├── screens
│   └── App
│       ├── components
│       ├── screens
│       │   ├── Admin
│       │   │   ├── components
│       │   │   ├── screens
│       │   │   │   ├── Reports
│       │   │   │   │   ├── components
│       │   │   │   │   ├── stores
│       │   │   │   │   │   └── ReportsStore.js
│       │   │   │   │   └── index.js
│       │   │   │   └── Users
│       │   │   │       ├── components
│       │   │   │       └── index.js
│       │   │   ├── shared
│       │   │   │   └── stores
│       │   │   │       ├── AccountStore.js
│       │   │   │       └── UserStore.js
│       │   │   └── index.js
│       │   └── Course
│       │       ├── components
│       │       ├── screens
│       │       │   └── Assignments
│       │       │       ├── components
│       │       │       └── index.js
│       │       └── index.js
│       ├── shared
│       │   └── components
│       │       ├── Avatar.js
│       │       └── Icon.js
│       └── index.js
├── shared
│   └── util
│       └── createStore.js
└── index.js

Tirei como base o seguinte artigo: https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346

**Comment by tuliofaria** [comment]
Acho que podemos usar sim esta forma, a única coisa que eu acredito que facilite para todos é utilizar o react-scripts (que vem com o create-react-app). Então, a única coisa que muda desta estrutura é de app para src :)

**Comment by angelorubin** [comment]
Uma outra sugestão de estrutura que costumo me inspirar descaradamente e que podemos nos basear também - https://github.com/codecasts/spa-starter-kit/tree/develop/client

**Comment by batistafrancis** [comment]
Então, fechamos na estrutura do @silvablack e `react-scripts` com `src` ?
